### ISSUE TITLE
After updating Flutter sdks to latest version the app have started to give Platform Exception

### ISSUE THREAD

**Issue by ars27196** [kishormainali/hive_local_storage#2]
Here is the exception :
```
PlatformException(Unexpected security result code, Code: -25299, Message: The specified item already exists in the keychain., -25299, null)
flutter: 
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
<asynchronous suspension>
#2      FlutterSecureStorage.write (package:flutter_secure_storage/flutter_secure_storage.dart:114:7)
<asynchronous suspension>
#3      LocalStorage._encryptionKey (package:hive_local_storage/src/hive_local_storage.dart:116:7)
<asynchronous suspension>
#4      LocalStorage._cipher (package:hive_local_storage/src/hive_local_storage.dart:106:12)
<asynchronous suspension>
#5      LocalStorage.getInstance.<anonymous closure> (package:hive_local_storage/src/hive_local_storage.dart:96:29)
<asynchronous suspension>
#6      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:36:16)
<asynchronous suspension>
#7      LocalStorage.getInstance (package:hive_local_storage/src/hive_local_storage.dart:91:5)
<asynchronous suspension>
#8      GetItHelper.lazySingletonAsy<…>
flutter: ----------------------------------------------------

```
My understanding is that since your package is dependent on FlutterSecureStorage, you need to update the lib to latest version. 
Following is my flutter doctor response:
```
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.5 23F79 darwin-arm64 (Rosetta), locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] IntelliJ IDEA Community Edition (version 2024.1.4)
[✓] VS Code (version 1.93.1)

```

**Comment by kishormainali** [comment]
Resolved in latest build
